name: Build and Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    permissions:
      contents: read
      pull-requests: write
    uses: Graphicscore/portainer-deploy-workflows/.github/workflows/actions.yml@master
    secrets:
      PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
      PORTAINER_TOKEN: ${{ secrets.PORTAINER_TOKEN }}
      CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

